config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  default_url_options :host => "example.com"

  root "public_recipes#index"
 
  resources :recipes, only: [:index, :show, :new, :destroy, :create, :update, :shopping] do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
    resources :shopping_lists, only: [:index]
  end
  resources :foods, only: [:index, :new, :create, :destroy]

  resources :public_recipes, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.confirmed_at?
      can :manage, :all
      can :destroy, Recipe do |recipe|
        recipe.user_id == user.id
      end
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true, length: { maximum: 100 }
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates_uniqueness_of :name
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 100 }
  validates :user_id, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true

  has_one_attached :image
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :recipe_id, presence: true
  validates :food_id, presence: true
  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy
  has_many :inventories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  # TODO: require user to login for all the actions
  before_action :authenticate_user!
  def index
    @foods = Food.all.where(user_id: current_user.id).order(created_at: :desc)
  end

  def show
    puts 'showing a spacific food'
  end

  def new
    @new_food = Food.new
  end

  def create
    @new_food = Food.new(user: current_user, name: params[:name], price: params[:price],
                         measurement_unit: params[:measurement_unit])
    @new_food.save!
    redirect_to foods_path
  end

  def destroy
    delete_food = Food.find(params[:id])
    RecipeFood.where(food: delete_food).destroy_all
    delete_food.destroy
    redirect_to foods_path
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.all.includes(:recipe_foods).where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  def new
    setup
  end

  def edit
    setup
    @recipe_food = RecipeFood.find(params[:id])
  end

  def create
    setup
    recipe_food = RecipeFood.new(recipe_food_params)
    recipe_food.recipe_id = params[:recipe_id]
    if recipe_food.save
      flash[:success] = 'Food was successfully added to recipe.'
    else
      flash[:danger] = 'Food was not added to recipe because <ul class="error-list">'
      recipe_food.errors.full_messages.each do |msg|
        flash[:danger] += "<li>#{msg}</li>"
      end
      flash[:danger] += '</ul>'
    end
    redirect_to recipe_path(params[:recipe_id])
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    respond_to do |format|
      format.html do
        flash[:success] = 'Recipe food deleted successfully'
        redirect_back_or_to({ action: 'show', id: params[:recipe_id] })
      end
    end
  end

  def update
    recipe_food = RecipeFood.find(params[:id])

    if recipe_food.update(recipe_food_update)
      flash[:success] = "quantity for #{recipe_food.food.name} was successfully updated."
    else
      flash[:danger] = 'operation failed <ul class="error-list">'
      recipe_food.errors.full_messages.each do |msg|
        flash[:danger] += "<li>#{msg}</li>"
      end
      flash[:danger] += '</ul>'
    end
    redirect_to recipe_path(params[:recipe_id])
  end

  def setup
    @recipe_food = RecipeFood.new
    @recipe_food_ids = RecipeFood.all.where(recipe_id: params[:recipe_id]).pluck(:food_id)
    @foods = Food.all.where(user_id: current_user.id).where.not(id: @recipe_food_ids).order(name: :asc)
    @recipe = Recipe.find(params[:recipe_id])
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end

  def recipe_food_update
    params.require(:recipe_food).permit(:quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  load_and_authorize_resource
  def destroy
    recipe = Recipe.find(params[:id])
    if recipe.destroy
      flash[:success] = 'Recipe deleted successfully'
    else
      flash.now[:danger] = 'Recipe deleted because <ul class="error-list">'
      recipe.errors.full_messages.each do |msg|
        flash[:danger] += "<li>#{msg}</li>"
      end
      flash[:danger] += '</ul>'
    end
    redirect_to recipes_url
  end

  def index
    @recipes = Recipe.all.where(user_id: current_user).order(created_at: :desc)
  end

  def show
    data = Recipe.where(id: params[:id]).with_attached_image
    @recipe = data[0]
    @recipe_foods = Food.all.joins('INNER JOIN recipe_foods ON foods.id = recipe_foods.food_id')
      .order(created_at: :desc).select('foods.*, recipe_foods.quantity, recipe_foods.id as recipe_foods_id')
      .where(recipe_foods: { recipe_id: params[:id] })
    return unless current_user
  end

  def new
    @user = current_user
    @recipe = @user.recipes.new
  end

  def create
    @user = current_user
    @recipe = @user.recipes.new(recipe_params)
    @recipe.preparation_time = "#{params[:recipe][:preparation_time]} minute(s)"
    @recipe.cooking_time = "#{params[:recipe][:cooking_time]} minute(s)"

    respond_to do |format|
      format.html do
        if @recipe.save
          flash[:success] = 'Recipe created successfully'
          redirect_to recipes_url
        else
          flash.now[:danger] = 'Recipe was not created because <ul class="error-list">'
          @recipe.errors.full_messages.each do |msg|
            flash.now[:danger] += "<li>#{msg}</li>"
          end
          flash.now[:danger] += '</ul>'
          render :new
        end
      end
    end
  end

  def sum(recipe_foods)
    total = 0
    recipe_foods.each do |rf_food|
      total += rf_food.food.price * rf_food.quantity.to_i
    end
    total
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :public, :description, :image)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def index
    @food = Food.all
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_foods = @recipe.recipe_foods.includes([:food])
    @total = sum(@recipe_foods)
  end

  def sum(recipe_foods)
    total = 0
    recipe_foods.each do |rf_food|
      total += rf_food.food.price * rf_food.quantity.to_i
    end
    total
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  layout 'user'
  def index
    User.all
  end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/index.html.erb
<h3 class="mb-3">Foods lists </h3>
<div class="table-responsive">
<table class="table table-striped text-center">
    <tr>
      <th>Food</th>
      <th>Measurement unit</th>
      <th>Unit price</th>
      <th>Action</th>
    </tr>
    <% @foods.each do |food| %>
    <tr>
      <td><%= food.name%></td>
      <td><%= food.measurement_unit%></td>
      <td><%= food.price%></td>
      <td><%= button_to 'Delete', food_path(id: food), method: :delete%></td>
    </tr>
    <% end %>
</table>
<%= button_to 'Add new food', new_food_path, method: :get%>
</div>

app/views/foods/new.html.erb
<div class="card-body transbox">
  <h1>Add new food here</h1>
  <%= form_with mode: @new_food, url: foods_path do |form| %>
    <div class="form-floating mb-3">
      <%= form.text_field :name, class: "form-control", required: true %>
      <%= form.label :name, "Name of Food *" %>
    </div>
    <div class="form-floating mb-3"  >
      <%= form.text_field :measurement_unit, class:"form-control" , required: true %>
      <%= form.label :measurement_unit, "Choose measuring unit *" %>
    </div>
    <div class="form-floating mb-3">
      <%= form.number_field :price, class: "form-control", required: true %>
      <%= form.label :price, "Unit price($) *" %>
    </div>  
    <div class="form-group mt-3">
      <%= form.submit '🥣 Add Food', class: "btn", style: "background-color: var(--primary-color); color: var(--secondary);", data: {disable_with: "Loading..."} %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <nav>
    <ul>  
      <li><label class ="logo"> Recipie App</label></li>
     <li><%= link_to ' Public Recipe'.html_safe, public_recipes_path  %> </li>
       <% if current_user %>
          <li><%= link_to ' Recipes'.html_safe, recipes_path  %> </li>
          <li><%= link_to ' Foods'.html_safe, foods_path  %></li>       
          <li class="right-side" style="float:right"><%= button_to 'Sign Out'.html_safe, destroy_user_session_path, method: :delete, :"data-turbolinks" => false %></li>  
        
        <% else %>
          <li class="right-side" style="float:right"><%= button_to 'Register'.html_safe, new_user_registration_path, method: :get, :"data-turbolinks" => false %></li>
          <li class="right-side" style="float:right"><%= button_to 'SignIn'.html_safe, new_user_session_path, method: :get, :"data-turbolinks" => false %></li>
         <% end %>
      </ul>
    <nav>
    <div class="content-body">
      <%= yield %>
    </div>
  </body>
</html>

app/views/public_recipes/index.html.erb
<h2>Public recipes</h2>
<% @public_recipes.each do |recipe| %>
<div class="card bg-light mb-6 align-center " style="margin:1%">
        <div class="card-header">Recipe</div>
        <div class="card-body element">
             <div class='element_left_recipes'>
               <%= recipe.name.capitalize %>
             </div>
            <div class='element_right'>  
                <p> Total food items: <%= @public_recipes.length %> </p>
                <p>Description: <%= truncate(recipe.description, length: 90, omission: '...') %></p>
               <p class="mt-6"> Total preparation_time: <%= recipe.preparation_time %> </p>
           </div>
        </div>
        <div class="card-footer bg-transparent border-success" style="display:flex">
            <%= link_to 'Detail'.html_safe, recipe_path(recipe.id), class: 'btn btn-outline-info' %>
        </div>
    </div>     
<% end %>

app/views/recipe_foods/new.html.erb
<%= render partial: "shared/recipe_food_form", locals: {recipe: @recipe, foods: @foods, method: 'post', recipe_food: @recipe_food, type: 'new', url: recipe_recipe_foods_path} %>

app/views/recipes/index.html.erb
<div class="header" style="display:flex; justify-content: space-between; margin:3% 0%">
<h1> Recipies</h1>
 <%= link_to ' + Create new '.html_safe, new_recipe_path, class: 'btn btn-primary ' %>
</div>
<div class="row">
    <% @recipes.each do |recipe| %>
    <div class="card bg-light mb-6 align-center " style="margin:1%">
        <div class="card-header"><%= recipe.name %></div>
        <div class="card-body element">
            <div class='element_left_recipes'>
               <%= recipe.name.capitalize %>
             </div>
            <div class='element_right'>  
                <p>Description: <%= truncate(recipe.description, length: 90, omission: '...') %></p>
               <p class="mt-6"> Total preparation_time: <%= recipe.preparation_time %> </p>
           </div>
        </div>
        <div class="card-footer bg-transparent border-success" style="display:flex">
            <%= link_to 'Show'.html_safe, recipe_path(recipe.id), class: 'btn btn-outline-info' %>
            <%= button_to "Delete", recipe_path(recipe.id), method: :delete , class: 'btn btn-outline-danger ml-1' if can? :destroy, recipe %>
        </div>
    </div>     
    <% end %>
</div>

</div>

app/views/recipes/new.html.erb
 <%= form_with model: @recipe, url: recipes_path do |f| %>
 <div class="mb-3">
                    <%= f.file_field :image, class: 'form-control' %>
                    <%= f.label :image, 'Choose an image that would appear as banner for recipe', class: 'mb-2' %>
                </div>
                <div class="form-floating mb-3">
                    <%= f.text_field :name, class: 'form-control', required: true %>
                    <%= f.label :name, "Recipe Name*" %>
                </div>
                <div class="form-floating mb-3">
                    <%= f.number_field :preparation_time, class: 'form-control', required: true %>
                    <%= f.label :preparation_time, "Preparation Time in mins*" %>
                </div>
                <div class="form-floating mb-3">
                    <%= f.number_field :cooking_time, class: 'form-control', required: true %>
                    <%= f.label :cooking_time, "Cooking Time in mins*" %>
                </div>
                <div class="form-floating mb-3">
                    <%= f.text_area :description, class: 'form-control' %>
                    <%= f.label :description, "Description" %>
                </div>
                <div class="form-check form-switch">
                    <%= f.check_box :public, class: "form-check-input" %>
                    <%= f.label :public, 'Mark public', class: "form-check-label" %> <br />
                    <i style="color: var(--primary-color)"> This allows other users to see your recipe</i>
                </div>
                <div class="form-group mt-3">
                    <%= f.submit '🥣 Create Recipe', class: "btn", style: "background-color: var(--primary-color); color: var(--white);", data: {disable_with: "Loading..."} %>
                </div>
                 <% end %>

app/views/recipes/show.html.erb
<div class="container">
    <div class="card text-center ">
        <h4 class="card-header" style="background: var(--primary-color); color: var(--white)">
          <%= image_tag @recipe.image, class: "float-start bio-photo" if @recipe.image.present? %>
          <%= @recipe.name %>
        </h4>
        <div class="row mx-5 mt-2">
          <div class="col-md-9">
              <p class="text-start"><i class="fa fa-clock-o" aria-hidden="true"></i> Preparation time: <%= @recipe.preparation_time %></p>
              <p class="text-start"><i class="fa fa-clock-o" aria-hidden="true"></i> Cooking time: <%= @recipe.cooking_time %></p> 
               <p class="text-start"><i class="fa fa-clock-o" aria-hidden="true"></i><u> Description</u>: <br> <%= @recipe.description %></p>
          </div>
          
            <div class="col-md-3">
                  <p class="text-start"><i class="fa fa-clock-o" aria-hidden="true"></i> Is public:  <%= @recipe.public %></p>
            </div>
        </div>
    </div>
    <% if current_user && @recipe.user_id == current_user.id %>
      <div class="mt-4">
          <button type="button"class='btn btn-outline-primary mb-2 flex-start' data-bs-toggle="modal" data-bs-target="#listBackdrop">
            <%= link_to '<i class="fa fa-plus" aria-hidden="true"></i> Generate shopping list '.html_safe, recipe_shopping_lists_path(@recipe.id), class: "btn btn-outline-success mb-2 flex-end" %> 
          </button>
          <span style="float: right">
            <%= link_to '<i class="fa fa-plus" aria-hidden="true"></i> Add food ingredient'.html_safe, new_recipe_recipe_food_path(@recipe.id), class: "btn btn-outline-success mb-2 flex-end" %> 
          </span>
      </div>
    <% end %>
    <table class="table table-striped text-center">
    <thead>
      <tr>
        <th class="text-center">#</th>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <% if current_user && @recipe.user_id == current_user.id %>
          <th>Action</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
          <% @recipe_foods.each do |recipe_food| %>
        <tr>
          <td>
             
          </td>
          <td><%= recipe_food.name %></td>
          <td><%= recipe_food.quantity %></td>
          <td>$<%= recipe_food.price * recipe_food.quantity %></td>
          <% if current_user && @recipe.user_id == current_user.id %>
            <td style = "display: flex; justify-content: space-evenly">              
                <%= button_to "Delete", recipe_recipe_food_path(@recipe.id, recipe_food.recipe_foods_id), method: :delete , class:'btn btn-outline-danger' %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_recipe_food_form.html.erb
<div class="row">
    <div class="mb-3 col-md-8 offset-md-2 inventory-card shadow">
        <div class="card-body">
        <% if type != 'edit' %>
            <h5>Add Ingredient to <%= recipe.name %></h5>
        <% else %>
            <h6>Updating <i> <%= recipe_food.food.name %> </i> in <%= recipe.name %></h6>
        <% end %>
        <%= form_with model: recipe_food, url: url, method: method, local: true do |form| %>
            <% if type != 'edit' %>
                <div class="form-floating mb-3">
                    <%= form.select :food_id, foods.map { |food| [food.name, food.id] }, {:include_blank => "-", :required => true}, {:class => 'form-control'} %>
                    <%= form.label :food_id, "Choose food from the list to add *" %>
                </div>
            <% end %>
            <div class="form-floating mb-3">
                <%= form.number_field :quantity, class: "form-control", required: true %>
                <%= form.label :quantity, "Quantity *" %>
            </div>
            <% if type != 'edit' %>
                <div class="form-group mt-3">
                    <%= form.submit 'Add Ingredient to recipe', class: "btn btn-primary", data: {disable_with: "Loading..."} %>
                </div>
            <% else %>
                <div class="form-group mt-3">
                    <%= form.submit "Update #{recipe_food.food.name}", class: "btn btn-primary", data: {disable_with: "Loading..."} %>
                </div>    
            <% end %>
        <% end %>
        </div>
  </div>
</div>

app/views/shopping_lists/index.html.erb
 <div class="card text-center ">
        <h4 class="card-header" style="background: var(--primary-color); color: var(--white)">
         Shopping Lists
        </h4>
        <div class="row mx-5 mt-2">
          <div class="col-md-9">
              <p class="text-start"><i class="fa fa-clock-o" aria-hidden="true"></i> Amount of food items to buy: <%= @recipe_foods.count %></p>
              <p class="text-start"><i class="fa fa-clock-o" aria-hidden="true"></i> Total price of food needed: <%= @total %></p> 
          </div>
         
        </div>
    </div>

<table class="table table-striped text-center">
    <thead>
      <tr>
         <th>Name</th>
      <th>Quantity</th>
      <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe_foods.each do |sp_food| %>
        <tr>
          <td><%= sp_food.food.name %></td>
          <td><%= sp_food.quantity %><%= sp_food.food.measurement_unit %></td>
          <td><span>$<%= (sp_food.food.price.to_i * sp_food.quantity.to_i)%></span></td>
      <% end %>
    </tbody>

app/views/users/index.html.erb
<h1>this is users index page</h1>